<a href="https://colab.research.google.com/github/jgoncsilva/Classes_IronHack/blob/master/numpy_class_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# numpy is to do math in python

mylist = [1,2,3,4,5]

# want to multiply all the numbers in my list be 2
# if lists were naturally made for maths in python
mylist*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
"hello"*2

'hellohello'

In [ ]:
import numpy as np
# let's create a numerical python library to do all the maths stuff to arrays of numbers

# think of difference between numpy as math

# how do I create a numpy array?

# turning my list (list object) into a numpy array
myarray = np.array(mylist)

# benefit from all the methods (tools) inside a numpy array object

In [ ]:
type(myarray)

numpy.ndarray

In [ ]:
# now the multiplication by two yields something which we ar used to
myarray*2

array([ 2,  4,  6,  8, 10])

In [ ]:
np.array([5.25,4,3,2,1])

array([5.25, 4.  , 3.  , 2.  , 1.  ])

In [ ]:
# what if I want to define numpy arrays without having fixed values, but with a fixed datatype?

a = np.zeros(5, dtype = float)

In [ ]:
a

array([0., 0., 0., 0., 0.])

In [ ]:
# what if I want more complex shapes?

a = np.zeros((5,2), dtype = float)

In [ ]:
a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
# numpy arrays can (and should and wil) be used to create and manipulate multi dimensional arrays

np.array([[1,2,3],[4,5,6.5],[7,8,9]],dtype = float)

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5],
       [7. , 8. , 9. ]])

In [ ]:
a = np.array([[[55,66,3],[40,90,3]],[[10,10,3],[10,11,3]],[[8,9,3],[6,7,3]],[[2,3,3],[3,4]]])

In [ ]:
# the shape method tells you what are the dimensions of your array
a.shape

(4, 2, 3)

In [ ]:
a

array([[[55, 66,  3],
        [40, 90,  3]],

       [[10, 10,  3],
        [10, 11,  3]],

       [[ 8,  9,  3],
        [ 6,  7,  3]],

       [[ 2,  3,  3],
        [ 3,  4,  3]]])

In [ ]:
# using random numbers in numpy

# generated a numpy array of 10 random numbers
np.random.random(10)

array([0.55697898, 0.28963509, 0.82784691, 0.31818359, 0.67083441,
       0.99341006, 0.62450308, 0.08057406, 0.31283869, 0.43539253])

In [ ]:
# generated an array of 500 random integers, the lowest possible being 18 the highest possible being 100
np.random.randint(18,100,500)



array([46, 30, 65, 84, 60, 30, 88, 94, 79, 40, 56, 77, 56, 99, 18, 55, 80,
       83, 35, 98, 39, 72, 52, 65, 30, 77, 23, 77, 70, 96, 19, 51, 49, 44,
       93, 76, 75, 78, 90, 72, 93, 56, 37, 94, 83, 39, 85, 35, 87, 29, 90,
       62, 57, 28, 34, 40, 42, 94, 30, 66, 58, 68, 36, 94, 66, 71, 85, 29,
       91, 80, 95, 49, 91, 46, 22, 72, 83, 93, 20, 21, 96, 88, 73, 32, 40,
       26, 40, 42, 99, 92, 67, 92, 27, 91, 40, 23, 84, 62, 60, 51, 73, 72,
       87, 93, 74, 34, 30, 71, 29, 62, 32, 79, 89, 77, 70, 58, 43, 50, 24,
       53, 26, 78, 90, 99, 55, 35, 26, 89, 33, 19, 26, 28, 91, 88, 58, 57,
       72, 38, 90, 70, 80, 29, 89, 26, 94, 66, 66, 20, 99, 94, 31, 40, 35,
       83, 83, 63, 74, 79, 86, 54, 28, 75, 76, 37, 66, 26, 77, 70, 56, 30,
       78, 97, 33, 91, 26, 61, 68, 60, 47, 74, 77, 38, 47, 80, 97, 31, 99,
       67, 83, 66, 95, 40, 52, 54, 50, 88, 67, 98, 50, 87, 23, 33, 84, 97,
       43, 85, 97, 43, 19, 45, 64, 31, 49, 90, 62, 91, 75, 51, 29, 20, 18,
       18, 55, 33, 27, 30

In [ ]:
# the last argument (size) you can control the shape of the genrated array
np.random.randint(0,10,(4,4))

array([[6, 5, 3, 3],
       [1, 2, 7, 3],
       [2, 9, 6, 1],
       [9, 5, 7, 3]])

In [ ]:
np.random.randint(5,size = (4,4))

array([[3, 1, 2, 1],
       [1, 2, 2, 3],
       [4, 0, 4, 4],
       [2, 0, 3, 0]])

In [ ]:
# generate a sequence of numbers
#equivalent to the built in range function

np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
array = np.random.randint(0,10,(4,4))
array

array([[6, 7, 2, 2],
       [9, 1, 5, 6],
       [8, 1, 8, 3],
       [2, 8, 9, 7]])

In [ ]:
# index it just like any other other iterable

array[0,2]

2

In [ ]:
array[0][2]

2

In [ ]:
array[[0,2,3]]

array([[6, 7, 2, 2],
       [8, 1, 8, 3],
       [2, 8, 9, 7]])

In [ ]:
# conditions in numpy arrays

a = np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
# applying the condition without having to iterate one by one :D 
a > 10

# he is applying the desired condition to each item in the array, and returning the anwer as a boolean

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [ ]:
condition = a >10

a[condition]

In [ ]:
# normally we are used to performing logical statements with "and" , "or"
# when slicing, we need to do & , | 
condition = (a > 10) & (a%2 == 0) 

In [ ]:
# using conditional slicing, to retrieve a subset of a numpy array, based on a condition
# filter
a[condition]

array([12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
a[a> 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29])

In [ ]:
#a[2::2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
a = np.random.randint(low = 0, high = 25, size =   (5,3))
a

array([[ 3,  7, 12],
       [ 0, 15,  8],
       [20, 23, 10],
       [10, 10, 10],
       [ 9,  8, 18]])

In [ ]:
# he evaluates the condition, element by elemebt KEEPING THE SHAPE
a >= 5

array([[False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
# when you use the condition as a slicer -> he returns everything to a 1D numpy array
a[a>=5]

array([ 7, 12, 15,  8, 20, 23, 10, 10, 10, 10,  9,  8, 18])

In [ ]:
a = np.random.randint(0,10,size = (3,10))
a

array([[1, 5, 8, 5, 3, 9, 0, 1, 7, 4],
       [8, 3, 0, 0, 5, 8, 2, 3, 1, 2],
       [0, 8, 2, 5, 7, 2, 3, 0, 7, 8]])

In [ ]:
a.transpose()

array([[1, 8, 0],
       [5, 3, 8],
       [8, 0, 2],
       [5, 0, 5],
       [3, 5, 7],
       [9, 8, 2],
       [0, 2, 3],
       [1, 3, 0],
       [7, 1, 7],
       [4, 2, 8]])

In [ ]:
# you can multiply numpy matrices -> Gonçalo's Homework

a

array([[1, 5, 8, 5, 3, 9, 0, 1, 7, 4],
       [8, 3, 0, 0, 5, 8, 2, 3, 1, 2],
       [0, 8, 2, 5, 7, 2, 3, 0, 7, 8]])

In [ ]:
# let's do some math
a.max()
a.mean()

3.9

In [ ]:
# he is taking the mean of each row, rather than of everything
a.mean(axis = 1)

array([4.3, 3.2, 4.2])

In [ ]:
# axis tells you the direction in which he perform the operation
a.mean(axis = 0)

array([3.        , 5.33333333, 3.33333333, 3.33333333, 5.        ,
       6.33333333, 1.66666667, 1.33333333, 5.        , 4.66666667])

In [ ]:
# the biggest power -> mathematical operations

# do every element in the array squared

a

array([[1, 5, 8, 5, 3, 9, 0, 1, 7, 4],
       [8, 3, 0, 0, 5, 8, 2, 3, 1, 2],
       [0, 8, 2, 5, 7, 2, 3, 0, 7, 8]])

In [ ]:
# he goes one by one and performs the square
np.square(a)

array([[ 1, 25, 64, 25,  9, 81,  0,  1, 49, 16],
       [64,  9,  0,  0, 25, 64,  4,  9,  1,  4],
       [ 0, 64,  4, 25, 49,  4,  9,  0, 49, 64]])

In [ ]:
a**2

array([[ 1, 25, 64, 25,  9, 81,  0,  1, 49, 16],
       [64,  9,  0,  0, 25, 64,  4,  9,  1,  4],
       [ 0, 64,  4, 25, 49,  4,  9,  0, 49, 64]])

In [ ]:
np.exp(a)

array([[2.71828183e+00, 1.48413159e+02, 2.98095799e+03, 1.48413159e+02,
        2.00855369e+01, 8.10308393e+03, 1.00000000e+00, 2.71828183e+00,
        1.09663316e+03, 5.45981500e+01],
       [2.98095799e+03, 2.00855369e+01, 1.00000000e+00, 1.00000000e+00,
        1.48413159e+02, 2.98095799e+03, 7.38905610e+00, 2.00855369e+01,
        2.71828183e+00, 7.38905610e+00],
       [1.00000000e+00, 2.98095799e+03, 7.38905610e+00, 1.48413159e+02,
        1.09663316e+03, 7.38905610e+00, 2.00855369e+01, 1.00000000e+00,
        1.09663316e+03, 2.98095799e+03]])

In [ ]:
# each element to the power of 4
np.power(a,4)

array([[   1,  625, 4096,  625,   81, 6561,    0,    1, 2401,  256],
       [4096,   81,    0,    0,  625, 4096,   16,   81,    1,   16],
       [   0, 4096,   16,  625, 2401,   16,   81,    0, 2401, 4096]])

In [ ]:
# EXTRA 
# lets test performance
import time

# defining a reallyyyyyyyyyyyyyyy big list of number
mynumbers = [i for i in range(0,100000)]

# counting
t1 = time.time()
# with an append
mylist = []
for i in mynumbers:
  mylist.append(i**2)
t2 = time.time()
print("with append ", t2-t1)

# with a list comp
mynumbers = [i for i in range(0,100000)]
t1 = time.time()
[i**2 for i in mynumbers]
t2 = time.time()
print("with list comprehension ", t2-t1)

# with a numpy array method
mynumbers = np.array(mynumbers)
t1 = time.time()
np.square(mynumbers)
t2 = time.time()

print("with numpy functions ", t2-t1)

#who is more efficient

In [ ]:
mynumbers = [i for i in range(0,1000000)]
import time

In [ ]:


# counting
t1 = time.time()
# with an append
mylist = []
for i in mynumbers:
  mylist.append(i**2)

t2 = time.time()
print("with append ", t2-t1)


with append  0.3723893165588379


In [ ]:
# with a list comp

t1 = time.time()
[i**2 for i in mynumbers]
t2 = time.time()
print("with list comprehension ", t2-t1)

with list comprehension  0.29508328437805176


In [ ]:
# with a numpy array method
mynumbers = np.array(mynumbers)
t1 = time.time()
np.square(mynumbers)
t2 = time.time()
print("with numpy functions ", t2-t1)

with numpy functions  0.0031120777130126953
